name = "anbox-iptv"
main = "src/anbox-iptv-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "853507b56b9537fc68fe461e6ce36ed9"

[[kv_namespaces]]
binding = "playlists"
id = "f734aec3a692476cad6c0b7eb03648cf"

[[kv_namespaces]]
binding = "portalist"
id = "5f1bf8a016184ba099055578c063789b"

[[workers.routes]]
pattern = "anbox-iptv.kkhk.workers.dev/*"
zone_name = "kkhk.workers.dev"
